/* Generated by python/export.py from python/dsp_ref.py. Do not edit. */
#ifndef COEFFS_H
#define COEFFS_H

#define HA_FS        48000
#define HA_LEVELS    4          /* split levels -> 5 bands */
#define HA_NG        21         /* G taps (Kaiser lowpass, cut fs_k/8) */
#define HA_DG        10         /* G group delay */
#define HA_NFE       16         /* even taps of the half-band F */
#define HA_DF_HALF   7          /* odd output times: y_(k+1) delayed by (15-1)/2 = 7 samples */
#define HA_L         128        /* Mode B new samples per block */
#define HA_NFFT      256        /* Mode B FFT size */
#define HA_NPRESET   4          /* N3, N2, S2, bypass */
#define HA_LIMIT     8.912509381e-01f /* output limiter, -1 dBFS */

extern const float HA_G[HA_NG];
extern const float HA_FE[HA_NFE];
extern const float HA_FC;                         /* centre tap of F (0.5) */
extern const float HA_HPF[2][5];                  /* b0 b1 b2 a1 a2 per biquad (a0 = 1) */
extern const int   HA_ALIGN[HA_LEVELS];           /* band alignment delays [365, 165, 65, 15] */
extern const float HA_GAIN[HA_NPRESET][HA_LEVELS + 1];   /* linear band gains B5..B1 */
extern const float HA_H[HA_NPRESET][2 * HA_NFFT];  /* Mode B H[k], re/im interleaved */
extern const char *const HA_PRESET_NAME[HA_NPRESET];

/* extras (off by default): feedback notch with howl detection, noise suppression */
#define HA_NOTCH_Q        10.000000
#define HA_HOWL_LO_HZ     500.0
#define HA_HOWL_HI_HZ     8000.0
#define HA_HOWL_PAPR_DB   25.000000
#define HA_HOWL_HOLD      75
#define HA_HOWL_FLOOR     1.000e-08
#define HA_HOWL_MAX       2
#define HA_NR_TAU_P       0.010000
#define HA_NR_TAU_G       0.020000
#define HA_NR_SUB         0.375000   /* s per sub-window */
#define HA_NR_NSUB        4
#define HA_NR_BETA        2.000000
#define HA_NR_GMIN        2.511886432e-01
#define HA_NR_NJ          65         /* frequency samples of the Mode B FIR */
#define HA_MB             129        /* Mode B FIR length */
extern const float HA_NR_BIAS_A[HA_LEVELS + 1];
extern const float HA_NR_BIAS_B;
extern const float HA_TGT[HA_NPRESET][HA_NR_NJ];  /* Mode B target magnitudes (linear) at k fs / 129 */

#endif
