"""Export coefficients (c/coeffs.c, c/coeffs.h) and PC test vectors (c/test/vectors/, git-ignored)
from the verified Python reference, so the C code and Python use identical numbers.

Run: python python/export.py   (c/build_pc.bat runs it automatically)
"""
import numpy as np
from scipy.io import wavfile
from dsp_ref import (ALIGN, DF, DG, F, FS, G, HPF_SOS, K, L_B, LIMIT, N_FFT, NG, PRESETS, ROOT, TEST_F,
                     band_gains, chain, fft_dit, goertzel, hpf, mode_a, mode_b, mode_b_H)

C = ROOT / "c"
VEC = C / "test" / "vectors"
VEC.mkdir(parents=True, exist_ok=True)
PRESET_ORDER = list(PRESETS)            # N3, N2, S2, bypass (button S3 order)


def arr(name, a, per_line=4, ctype="float"):
    a = np.asarray(a).ravel()
    body = ",\n".join("    " + ", ".join(f"{v: .9e}f" for v in a[i:i + per_line]) for i in range(0, len(a), per_line))
    return f"const {ctype} {name}[{len(a)}] = {{\n{body}\n}};\n"


# ---------------------------------------------------------------- coefficients
Fe = F[0::2]
assert np.all(F[1::2][np.arange(len(F[1::2])) != DF // 2] == 0)   # half-band: odd taps zero except centre
gains = np.array([10 ** (band_gains(p) / 20) for p in PRESET_ORDER])
H = np.array([mode_b_H(p) for p in PRESET_ORDER])                  # 4 x 256 complex
Hil = np.stack([H.real, H.imag], axis=-1).reshape(len(PRESET_ORDER), 2 * N_FFT)

hdr = f"""/* Generated by python/export.py from python/dsp_ref.py. Do not edit. */
#ifndef COEFFS_H
#define COEFFS_H

#define HA_FS        {int(FS)}
#define HA_LEVELS    {K}          /* split levels -> {K + 1} bands */
#define HA_NG        {NG}         /* G taps (Kaiser lowpass, cut fs_k/8) */
#define HA_DG        {DG}         /* G group delay */
#define HA_NFE       {len(Fe)}         /* even taps of the half-band F */
#define HA_DF_HALF   {DF // 2}          /* odd output times: y_(k+1) delayed by (15-1)/2 = 7 samples */
#define HA_L         {L_B}        /* Mode B new samples per block */
#define HA_NFFT      {N_FFT}        /* Mode B FFT size */
#define HA_NPRESET   {len(PRESET_ORDER)}          /* {", ".join(PRESET_ORDER)} */
#define HA_LIMIT     {LIMIT:.9e}f /* output limiter, -1 dBFS */

extern const float HA_G[HA_NG];
extern const float HA_FE[HA_NFE];
extern const float HA_FC;                         /* centre tap of F (0.5) */
extern const float HA_HPF[2][5];                  /* b0 b1 b2 a1 a2 per biquad (a0 = 1) */
extern const int   HA_ALIGN[HA_LEVELS];           /* band alignment delays {ALIGN} */
extern const float HA_GAIN[HA_NPRESET][HA_LEVELS + 1];   /* linear band gains B5..B1 */
extern const float HA_H[HA_NPRESET][2 * HA_NFFT];  /* Mode B H[k], re/im interleaved */
extern const char *const HA_PRESET_NAME[HA_NPRESET];

#endif
"""
src = '/* Generated by python/export.py from python/dsp_ref.py. Do not edit. */\n#include "coeffs.h"\n\n'
src += arr("HA_G", G)
src += arr("HA_FE", Fe)
src += f"const float HA_FC = {F[DF]:.9e}f;\n"
src += "const float HA_HPF[2][5] = {\n" + ",\n".join(
    "    {" + ", ".join(f"{v: .9e}f" for v in (s[0], s[1], s[2], s[4], s[5])) + "}" for s in HPF_SOS) + "\n};\n"
src += "const int HA_ALIGN[HA_LEVELS] = {" + ", ".join(map(str, ALIGN)) + "};\n"
src += "const float HA_GAIN[HA_NPRESET][HA_LEVELS + 1] = {\n" + ",\n".join(
    "    {" + ", ".join(f"{v:.9e}f" for v in g) + "}" for g in gains) + "\n};\n"
src += "#ifdef __TI_COMPILER_VERSION__\n#pragma DATA_ALIGN(HA_H, 8)\n#endif\n"
src += "const float HA_H[HA_NPRESET][2 * HA_NFFT] = {\n" + ",\n".join(
    "  {\n" + ",\n".join("    " + ", ".join(f"{v: .9e}f" for v in row[i:i + 4]) for i in range(0, len(row), 4)) + "\n  }"
    for row in Hil) + "\n};\n"
src += "const char *const HA_PRESET_NAME[HA_NPRESET] = {" + ", ".join(f'"{p}"' for p in PRESET_ORDER) + "};\n"
(C / "coeffs.h").write_text(hdr, newline="\n")
(C / "coeffs.c").write_text(src, newline="\n")

# ---------------------------------------------------------------- test vectors (float64 raw, little endian)
rng = np.random.default_rng(11)
_, sp = wavfile.read(ROOT / "data" / "speech_48k.wav")
s = sp[48000:48000 + int(1.5 * FS)].astype(float) / 32768
s *= 10 ** (-40 / 20) / np.sqrt(np.mean(s ** 2))
imp = np.zeros(4800); imp[100] = 0.25
noise = 0.01 * rng.standard_normal(int(0.5 * FS))
loud = 0.5 * np.sin(2 * np.pi * 1000 * np.arange(int(0.2 * FS)) / FS)         # exercises the limiter
x = np.concatenate([imp, s, noise, loud])
x = np.round(x * 32768).clip(-32768, 32767) / 32768                             # codec samples (16-bit)
x = x[: len(x) // L_B * L_B]
x.tofile(VEC / "in.f64")
hpf(x).tofile(VEC / "hpf.f64")
mode_a(x, band_gains("N3")).tofile(VEC / "modeA_N3.f64")
mode_b(x, "N3").tofile(VEC / "modeB_N3.f64")
for p in PRESET_ORDER:
    chain(x, "A", p).tofile(VEC / f"chainA_{p}.f64")
    chain(x, "B", p).tofile(VEC / f"chainB_{p}.f64")
z = rng.standard_normal(2 * N_FFT)
z.tofile(VEC / "fft_in.f64")
Z = fft_dit(z[0::2] + 1j * z[1::2])
np.stack([Z.real, Z.imag], -1).ravel().tofile(VEC / "fft_out.f64")
t = np.arange(4608) / FS
tones = np.array([0.1 * np.sin(2 * np.pi * f * t + 0.3) for f in TEST_F])
tones.tofile(VEC / "goertzel_in.f64")
np.array([goertzel(v, f) for v, f in zip(tones, TEST_F)]).tofile(VEC / "goertzel_out.f64")
# ---------------------------------------------------------------- board stored signal (CCS Load Memory)
# 2 s of speech at -40 dBFS RMS as 32-bit words holding 16-bit samples (g_stored in board_io.c).
# TI data format: header "1651 <format=1 hex> <start address> <page> <length in words>", one word per line.
BOARD = ROOT / "data" / "board"
BOARD.mkdir(parents=True, exist_ok=True)
st = sp[: 96000].astype(float) / 32768
st = np.round(st * 10 ** (-40 / 20) / np.sqrt(np.mean(st ** 2)) * 32768).clip(-32768, 32767).astype(np.int32)
with open(BOARD / "speech_stored.dat", "w", newline="\n") as f:
    f.write(f"1651 1 c0000000 0 {len(st):x}\n")
    f.writelines(f"0x{v:08X}\n" for v in st.view(np.uint32).tolist())   # two's complement words
st.astype("<i4").tofile(BOARD / "speech_stored.bin")
# input-channel check (board checklist step 4): 1 kHz at -20 dBFS on one channel only, 10 s
tt = np.arange(10 * 48000) / FS
tone = (0.1 * 32767 * np.sin(2 * np.pi * 1000 * tt)).astype(np.int16)
z0 = np.zeros_like(tone)
wavfile.write(BOARD / "tone1k_left_only.wav", 48000, np.stack([tone, z0], 1))
wavfile.write(BOARD / "tone1k_right_only.wav", 48000, np.stack([z0, tone], 1))
print(f"coeffs.c/h written; {len(x)} test samples ({len(x)/FS:.2f} s) and expected outputs in c/test/vectors/")
