"""Export coefficients (c/coeffs.c, c/coeffs.h) and PC test vectors (c/test/vectors/, git-ignored)
from the verified Python reference, so the C code and Python use identical numbers.

Run: python python/export.py   (c/build_pc.bat runs it automatically)
"""
import numpy as np
from scipy.io import wavfile
import dsp_ref as R
from dsp_ref import (ALIGN, DF, DG, F, FS, G, HPF_SOS, K, L_B, LIMIT, N_FFT, NG, PRESETS, ROOT, TEST_F,
                     band_gains, chain, fft_dit, goertzel, hpf, mode_a, mode_b, mode_b_H, notch_auto, target_db)

C = ROOT / "c"
VEC = C / "test" / "vectors"
VEC.mkdir(parents=True, exist_ok=True)
PRESET_ORDER = list(PRESETS)            # N3, N2, S2, bypass (button S3 order)


def arr(name, a, per_line=4, ctype="float"):
    a = np.asarray(a).ravel()
    body = ",\n".join("    " + ", ".join(f"{v: .9e}f" for v in a[i:i + per_line]) for i in range(0, len(a), per_line))
    return f"const {ctype} {name}[{len(a)}] = {{\n{body}\n}};\n"


# ---------------------------------------------------------------- coefficients
Fe = F[0::2]
assert np.all(F[1::2][np.arange(len(F[1::2])) != DF // 2] == 0)   # half-band: odd taps zero except centre
gains = np.array([10 ** (band_gains(p) / 20) for p in PRESET_ORDER])
H = np.array([mode_b_H(p) for p in PRESET_ORDER])                  # 4 x 256 complex
Hil = np.stack([H.real, H.imag], axis=-1).reshape(len(PRESET_ORDER), 2 * N_FFT)

hdr = f"""/* Generated by python/export.py from python/dsp_ref.py. Do not edit. */
#ifndef COEFFS_H
#define COEFFS_H

#define HA_FS        {int(FS)}
#define HA_LEVELS    {K}          /* split levels -> {K + 1} bands */
#define HA_NG        {NG}         /* G taps (Kaiser lowpass, cut fs_k/8) */
#define HA_DG        {DG}         /* G group delay */
#define HA_NFE       {len(Fe)}         /* even taps of the half-band F */
#define HA_DF_HALF   {DF // 2}          /* odd output times: y_(k+1) delayed by (15-1)/2 = 7 samples */
#define HA_L         {L_B}        /* Mode B new samples per block */
#define HA_NFFT      {N_FFT}        /* Mode B FFT size */
#define HA_NPRESET   {len(PRESET_ORDER)}          /* {", ".join(PRESET_ORDER)} */
#define HA_LIMIT     {LIMIT:.9e}f /* output limiter, -1 dBFS */

extern const float HA_G[HA_NG];
extern const float HA_FE[HA_NFE];
extern const float HA_FC;                         /* centre tap of F (0.5) */
extern const float HA_HPF[2][5];                  /* b0 b1 b2 a1 a2 per biquad (a0 = 1) */
extern const int   HA_ALIGN[HA_LEVELS];           /* band alignment delays {ALIGN} */
extern const float HA_GAIN[HA_NPRESET][HA_LEVELS + 1];   /* linear band gains B5..B1 */
extern const float HA_H[HA_NPRESET][2 * HA_NFFT];  /* Mode B H[k], re/im interleaved */
extern const char *const HA_PRESET_NAME[HA_NPRESET];

/* extras (off by default): feedback notch with howl detection, noise suppression */
#define HA_NOTCH_Q        {R.NOTCH_Q:.6f}
#define HA_HOWL_LO_HZ     {R.HOWL_LO:.1f}
#define HA_HOWL_HI_HZ     {R.HOWL_HI:.1f}
#define HA_HOWL_PAPR_DB   {R.HOWL_PAPR_DB:.6f}
#define HA_HOWL_HOLD      {R.HOWL_HOLD}
#define HA_HOWL_FLOOR     {R.HOWL_FLOOR:.3e}
#define HA_HOWL_MAX       {R.HOWL_MAX}
#define HA_NR_TAU_P       {R.NR_TAU_P:.6f}
#define HA_NR_TAU_G       {R.NR_TAU_G:.6f}
#define HA_NR_SUB         {R.NR_SUB:.6f}   /* s per sub-window */
#define HA_NR_NSUB        {R.NR_NSUB}
#define HA_NR_BETA        {R.NR_BETA:.6f}
#define HA_NR_GMIN        {R.NR_GMIN:.9e}
#define HA_NR_NJ          {len(R.NR_J)}         /* frequency samples of the Mode B FIR */
#define HA_MB             {R.M_B}        /* Mode B FIR length */
extern const float HA_NR_BIAS_A[HA_LEVELS + 1];
extern const float HA_NR_BIAS_B;
extern const float HA_TGT[HA_NPRESET][HA_NR_NJ];  /* Mode B target magnitudes (linear) at k fs / 129 */

#endif
"""
src = '/* Generated by python/export.py from python/dsp_ref.py. Do not edit. */\n#include "coeffs.h"\n\n'
src += arr("HA_G", G)
src += arr("HA_FE", Fe)
src += f"const float HA_FC = {F[DF]:.9e}f;\n"
src += "const float HA_HPF[2][5] = {\n" + ",\n".join(
    "    {" + ", ".join(f"{v: .9e}f" for v in (s[0], s[1], s[2], s[4], s[5])) + "}" for s in HPF_SOS) + "\n};\n"
src += "const int HA_ALIGN[HA_LEVELS] = {" + ", ".join(map(str, ALIGN)) + "};\n"
src += "const float HA_GAIN[HA_NPRESET][HA_LEVELS + 1] = {\n" + ",\n".join(
    "    {" + ", ".join(f"{v:.9e}f" for v in g) + "}" for g in gains) + "\n};\n"
src += "#ifdef __TI_COMPILER_VERSION__\n#pragma DATA_ALIGN(HA_H, 8)\n#endif\n"
src += "const float HA_H[HA_NPRESET][2 * HA_NFFT] = {\n" + ",\n".join(
    "  {\n" + ",\n".join("    " + ", ".join(f"{v: .9e}f" for v in row[i:i + 4]) for i in range(0, len(row), 4)) + "\n  }"
    for row in Hil) + "\n};\n"
src += "const char *const HA_PRESET_NAME[HA_NPRESET] = {" + ", ".join(f'"{p}"' for p in PRESET_ORDER) + "};\n"
src += arr("HA_NR_BIAS_A", R.NR_BIAS_A)
src += f"const float HA_NR_BIAS_B = {R.NR_BIAS_B:.9e}f;\n"
tg = np.array([10 ** (target_db(p, R.NR_J * FS / R.M_B) / 20) for p in PRESET_ORDER])
src += "const float HA_TGT[HA_NPRESET][HA_NR_NJ] = {\n" + ",\n".join(
    "  {\n" + ",\n".join("    " + ", ".join(f"{v:.9e}f" for v in row[i:i + 4]) for i in range(0, len(row), 4)) + "\n  }"
    for row in tg) + "\n};\n"
(C / "coeffs.h").write_text(hdr, newline="\n")
(C / "coeffs.c").write_text(src, newline="\n")

# ---------------------------------------------------------------- test vectors (float64 raw, little endian)
rng = np.random.default_rng(11)
_, sp = wavfile.read(ROOT / "data" / "speech_48k.wav")
s = sp[48000:48000 + int(1.5 * FS)].astype(float) / 32768
s *= 10 ** (-40 / 20) / np.sqrt(np.mean(s ** 2))
imp = np.zeros(4800); imp[100] = 0.25
noise = 0.01 * rng.standard_normal(int(0.5 * FS))
loud = 0.5 * np.sin(2 * np.pi * 1000 * np.arange(int(0.2 * FS)) / FS)         # exercises the limiter
x = np.concatenate([imp, s, noise, loud])
x = np.round(x * 32768).clip(-32768, 32767) / 32768                             # codec samples (16-bit)
x = x[: len(x) // L_B * L_B]
x.tofile(VEC / "in.f64")
hpf(x).tofile(VEC / "hpf.f64")
mode_a(x, band_gains("N3")).tofile(VEC / "modeA_N3.f64")
mode_b(x, "N3").tofile(VEC / "modeB_N3.f64")
for p in PRESET_ORDER:
    chain(x, "A", p).tofile(VEC / f"chainA_{p}.f64")
    chain(x, "B", p).tofile(VEC / f"chainB_{p}.f64")
# extras test: speech + white noise (10 dB SNR) + a 2.5 kHz "howl" from 0.6 s, through NR + auto notch
s2 = sp[48000:48000 + int(2.0 * FS)].astype(float) / 32768
s2 *= 10 ** (-40 / 20) / np.sqrt(np.mean(s2 ** 2))
tt2 = np.arange(len(s2)) / FS
x2 = s2 + 0.01 * 10 ** (-10 / 20) * rng.standard_normal(len(s2)) + \
     np.where(tt2 >= 0.6, np.sqrt(2) * 10 ** (-30 / 20) * np.sin(2 * np.pi * 2500 * tt2), 0)
x2 = np.round(x2 * 32768).clip(-32768, 32767) / 32768
x2 = x2[: len(x2) // L_B * L_B]
x2.tofile(VEC / "in_x.f64")
ev = []
notch_auto(hpf(x2), ev)
np.array([v for e in ev for v in e], float).tofile(VEC / "notch_events.f64")   # (sample, Hz) pairs
for mode in "AB":
    chain(x2, mode, "N3", nr=True, notch=True).tofile(VEC / f"chain{mode}_N3_extras.f64")
    chain(x2, mode, "N3", nr=True).tofile(VEC / f"chain{mode}_N3_nr.f64")
z = rng.standard_normal(2 * N_FFT)
z.tofile(VEC / "fft_in.f64")
Z = fft_dit(z[0::2] + 1j * z[1::2])
np.stack([Z.real, Z.imag], -1).ravel().tofile(VEC / "fft_out.f64")
t = np.arange(4608) / FS
tones = np.array([0.1 * np.sin(2 * np.pi * f * t + 0.3) for f in TEST_F])
tones.tofile(VEC / "goertzel_in.f64")
np.array([goertzel(v, f) for v, f in zip(tones, TEST_F)]).tofile(VEC / "goertzel_out.f64")
# ---------------------------------------------------------------- board stored signal (CCS Load Memory)
# 2 s of speech at -40 dBFS RMS as 32-bit words holding 16-bit samples (g_stored in board_io.c).
# TI data format: header "1651 <format=1 hex> <start address> <page> <length in words>", one word per line.
BOARD = ROOT / "data" / "board"
BOARD.mkdir(parents=True, exist_ok=True)
st = sp[: 96000].astype(float) / 32768
st = np.round(st * 10 ** (-40 / 20) / np.sqrt(np.mean(st ** 2)) * 32768).clip(-32768, 32767).astype(np.int32)
with open(BOARD / "speech_stored.dat", "w", newline="\n") as f:
    f.write(f"1651 1 c0000000 0 {len(st):x}\n")
    f.writelines(f"0x{v:08X}\n" for v in st.view(np.uint32).tolist())   # two's complement words
st.astype("<i4").tofile(BOARD / "speech_stored.bin")
# the same 2 s compiled into the board program (STORED_SPEECH builds: no Load Memory step needed)
clip = "/* Generated by python/export.py: 2 s of test speech (Windows TTS, data/speech_48k.wav), -40 dBFS RMS,\n" \
       " * 16-bit, for the STORED_SPEECH builds. Do not edit. */\n#pragma DATA_SECTION(HA_SPEECH, \".ddr_const\")\n" \
       f"const short HA_SPEECH[{len(st)}] = {{\n" + ",\n".join(
           "  " + ",".join(f"{int(v)}" for v in st[i:i + 20]) for i in range(0, len(st), 20)) + "\n};\n"
(ROOT / "ccs" / "hearing_aid" / "speech_clip.c").write_text(clip, newline="\n")
# input-channel check (board checklist step 4): 1 kHz at -20 dBFS on one channel only, 10 s
tt = np.arange(10 * 48000) / FS
tone = (0.1 * 32767 * np.sin(2 * np.pi * 1000 * tt)).astype(np.int16)
z0 = np.zeros_like(tone)
wavfile.write(BOARD / "tone1k_left_only.wav", 48000, np.stack([tone, z0], 1))
wavfile.write(BOARD / "tone1k_right_only.wav", 48000, np.stack([z0, tone], 1))
# live-test signals to play from the PC (board checklist step 7); both channels carry the same signal.
# Each file starts with 0.5 s silence + a single click (alignment marker) + 0.5 s silence.
dith = np.random.default_rng(5)


def board_wav(name, sig):
    lead = np.zeros(int(1.0 * FS)); lead[int(0.5 * FS)] = 0.5
    v = np.concatenate([lead, sig, np.zeros(int(0.5 * FS))])
    # TPDF dither (+-1 LSB): turns 16-bit quantisation of quiet tones into noise instead of harmonics
    tpdf = dith.uniform(-0.5, 0.5, len(v)) + dith.uniform(-0.5, 0.5, len(v))
    w = np.round(np.clip(v, -1, 1) * 32767 + tpdf).clip(-32768, 32767).astype(np.int16)
    wavfile.write(BOARD / name, 48000, np.stack([w, w], 1))


amp40 = np.sqrt(2) * 10 ** (-40 / 20)                                   # -40 dBFS RMS sine
board_wav("T2_tones.wav", np.concatenate([amp40 * np.sin(2 * np.pi * f * np.arange(int(FS)) / FS) for f in TEST_F]))
board_wav("T4_noise.wav", 0.01 * np.random.default_rng(4).standard_normal(int(10 * FS)))
clk = np.zeros(int(5 * FS)); clk[::int(0.5 * FS)] = 0.25                 # T5: 10 clicks, 0.5 s apart
board_wav("T5_clicks.wav", clk)
board_wav("T9_spur_tones.wav", np.concatenate([amp40 * np.sin(2 * np.pi * f * np.arange(int(FS)) / FS)
                                               for f in (700, 760, 1450, 1550, 2950, 3050, 5900, 6100)]))
board_wav("T10_level_steps.wav", np.concatenate([10 ** (l / 20) * np.sqrt(2) * np.sin(2 * np.pi * 1000 * np.arange(int(FS)) / FS)
                                                  for l in range(-40, 1, 5)]))
print(f"coeffs.c/h written; {len(x)} test samples ({len(x)/FS:.2f} s) and expected outputs in c/test/vectors/")
